littleguys/urls.py
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
#import dajaxice.core as dja
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
admin.autodiscover()
dajaxice_autodiscover()

#import sys
#sys.path.append('/usr/local/lib/python2.7/site-packages')
#import dajaxice.core as dja
#from inspect import getmembers
#print getmembers(dja)

urlpatterns = patterns('',
    # This will match any url of the form /lilguys/lilguy_name, where
    # lilguy_name is the name of a lilguy (matches any non / character).
    # This page will display all information about a guy.
    url(r'^$', 'guytracker.views.all_guys'),
    # AJAX endpoints here
    url(r'^dajaxice/', include('dajaxice.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    url(r'^g/(?P<url_code>[^/]+)/', 'guytracker.views.display_guy'),
    # Examples:
    url(r'^lilguys/g/(?P<url_code>[^/]+)/', 'guytracker.views.display_guy'),
    url(r'^about$', 'guytracker.views.about_us'),
    # url(r'^$', 'littleguys.views.home', name='home'),
    # url(r'^littleguys/', include('littleguys.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                    'document_root': settings.MEDIA_ROOT}),
        (r'/lg/media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}))

guytracker/models.py
from django.core.files import File
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.files.base import ContentFile
from django.db import models
from PIL import Image
import StringIO

class Lilguy(models.Model):
    """ A little guy ready for adventure. """

    # the name of the little guy
    name = models.CharField(max_length=55)
    # the icon/avatar photo of the little guy
    pic = models.ImageField(upload_to="lilguybook", max_length=200)    
    # the icon/avatar shrunk to 180px width.
    pic_180 = models.ImageField(upload_to="lilguybook/180", max_length=200, null=True, blank=True)
    # longitude and latitude positions of most recently logged location
    current_lon = models.FloatField()
    current_lat = models.FloatField()
    # Timestamp
    timestamp = models.DateTimeField(auto_now_add=True)
     
    def save(self, *args, **kwargs):
        """Override save to resize pic field."""
        if self.pic:
            EXTRA_IMAGE_SIZES = {'pic_180': (180, 270)}
            MAX_SIZE = (1280, 1280)
            imgFile = Image.open(StringIO.StringIO(self.pic.read()))
            #Convert to RGB
            if imgFile.mode not in ('L', 'RGB'):
                imgFile = imgFile.convert('RGB')
            for field_name, size in EXTRA_IMAGE_SIZES.iteritems():
                field = getattr(self, field_name)
                working = imgFile.copy()
                working.thumbnail(size, Image.ANTIALIAS)
                fp = StringIO.StringIO()
                working.save(fp, format="JPEG", quality=95)
                cf = ContentFile(fp.getvalue())
                field.save(name=self.pic.name, content=cf, save=False)
            imgFile.thumbnail(MAX_SIZE, Image.ANTIALIAS)
            output = StringIO.StringIO()
            imgFile.save(output, format="JPEG", quality=95)
            output.seek(0)
            self.pic = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.pic.name.split('.')[0], 'image/jpeg', output.len, None)
        
        super(Lilguy, self).save(*args, **kwargs)

    def __unicode__(self):
        return ("Lilguy: " + self.name + 
                ", "
                "currently located at (" + 
                str(self.current_lon) + ", " + 
                str(self.current_lat) + ") " )


class Chapter(models.Model):
    """Describes a user-created chapter in a Lilguy's life."""
    # The Lilguy that this chapter is about.
    lilguy = models.ForeignKey(Lilguy)
    # The (optional) title of the story. We default to a date?
    title = models.CharField(max_length=80, null=True, blank=True)
    # The story text.
    story_text = models.TextField()
    # The longitude at which the guy was found.
    found_at_lon = models.FloatField()
    # The latitude at which the guy was found
    found_at_lat = models.FloatField()
    # The longitude that the person plans to drop the guy near.
    dropped_at_lon = models.FloatField(null=True, blank=True)
    # The latitude that the person plans to drop the guy near.
    dropped_at_lat = models.FloatField(null=True, blank=True)
    # The author can include a picture of the guy.
    picture = models.ImageField(upload_to='adventures', max_length=200, null=True, blank=True)
    # Thumbs for the picture. Used on the site.
    picture_600 = models.ImageField(upload_to='adventures/600', 
                                    max_length=200, 
                                    null=True, 
                                    blank=True)
    # Timestamp
    timestamp = models.DateTimeField(auto_now_add=True)
    # Submiter's email(if subscribed)
    email = models.EmailField(max_length=254, null=True, blank=True)
    
    def save(self, *args, **kwargs):
        """Override save to resize picture field."""
        if self.picture:
            EXTRA_IMAGE_SIZES = {'picture_600': (600, 900)}
            MAX_SIZE = (1280, 1280)
            imgFile = Image.open(StringIO.StringIO(self.picture.read()))
            #Convert to RGB
            if imgFile.mode not in ('L', 'RGB'):
                imgFile = imgFile.convert('RGB')
            for field_name, size in EXTRA_IMAGE_SIZES.iteritems():
                field = getattr(self, field_name)
                working = imgFile.copy()
                working.thumbnail(size, Image.ANTIALIAS)
                fp = StringIO.StringIO()
                working.save(fp, format="JPEG", quality=95)
                cf = ContentFile(fp.getvalue())
                field.save(name=self.picture.name, content=cf, save=False)
            imgFile.thumbnail(MAX_SIZE, Image.ANTIALIAS)
            output = StringIO.StringIO()
            imgFile.save(output, format="JPEG", quality=95)
            output.seek(0)
            self.picture = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.picture.name.split('.')[0], 'image/jpeg', output.len, None)

        super(Chapter, self).save(*args, **kwargs)

    def __unicode__(self):
        return ("Chapter(title=" + self.title + 
                "lilguy.name=" + self.lilguy.name +
                ", story_text=" + self.story_text +
                ", found_at_lon=" + str(self.found_at_lon) +
                ", found_at_lat=" + str(self.found_at_lat) +
                ", dropped_at_lon=" + str(self.dropped_at_lon) +
                ", dropped_at_lat=" + str(self.dropped_at_lat))

guytracker/forms.py
from django import forms
from django.db import models
from guytracker.models import Chapter

class ChapterForm(forms.ModelForm):
    class Meta:
        model = Chapter
        exclude = ['lilguy', 'timestamp', 'dropped_at_lat', 'dropped_at_lon']
        widgets = {'found_at_lat': forms.HiddenInput(),
                   'found_at_lon': forms.HiddenInput()}
    code = forms.CharField(max_length=6, widget=forms.HiddenInput())
    
    def clean_picture(self):
        """Custom validation for the picture field"""
        image = self.cleaned_data.get('picture', False)
        if image:
            if image._size > 10*1024*1024:
                raise forms.ValidationError("Image file too large ( > 10mb )")
            return image

guytracker/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from guytracker.forms import ChapterForm
import guytracker.messages as msg
from guytracker.models import Lilguy, Chapter
import guytracker.utils as ut
import json

def all_guys(request):
    """
    Give a list of all guys.
    """
    lilguys = Lilguy.objects.all()
    # A dictionary of url_code -> (name, pic)
    lilguy_url_code_to_name_pic = {}
    for guy in lilguys:
        lilguy_url_code_to_name_pic[ut.lilguy_id_to_urlsafe_code(guy.id)] = (guy.name, guy.pic_180)
        # uncomment to print out secret codes of guys
        # print "name: " + str(guy.name) + ", url_code: " + ut.lilguy_id_to_urlsafe_code(guy.id) + ", secret_code: " + ut.lilguy_id_to_activation_code(guy.id)

    # We pass a (cleanned) JS version of the lilguys object,
    # so that client code can use it dynamically.
    lilguys_js = ut.lilguys_to_JS(lilguys)

    # get three most recent guy stories
    recent_chapters = Chapter.objects.select_related().order_by('-id')[:3]
    coord_request = []
    for chapter in recent_chapters:
        chapter.url = ut.lilguy_id_to_urlsafe_code(chapter.lilguy.id)
        chapter.location = ut.coords_to_location_name(chapter.found_at_lat, chapter.found_at_lon)

    return render_to_response('all_guys.html', 
                              {'lilguy_url_code_to_name_pic': lilguy_url_code_to_name_pic,
                               'lilguys_js': lilguys_js,
                               'recent_chapters': recent_chapters},
                              context_instance=RequestContext(request))

def display_guy(request, url_code):
    """ Returns an HttpResponse for an individual lilguy's information \
        and chapters page. """
    # If the param is empty, send them the all_guys page instead.
    if not url_code:
        return all_guys(request)

    # The pk id of the lilguy being requested:
    id = ut.urlsafe_code_to_lilguy_id(url_code)
    # The true activation code:
    secret_code = ut.lilguy_id_to_activation_code(id)
    # True if the user has already written a chapter for this guy:
    already_written = request.session.get('has_made_chapter_'+url_code, False)
    # If the user already entered the activation
    # code, we store it to propogate it on the next page. This is used because
    # we want a good UX for form validation.
    user_entered_code = ''
    # Uncomment below for helpful log of PMH codes.
    #print "id: " + str(id) + ", url_code: " + url_code + ", secret_code: " + secret_code
    lilguy = Lilguy.objects.get(id=id)    
    # finds all Chapters about this lilguy
    chapters = (Chapter.objects.select_related()
                .filter(lilguy=lilguy)
                .order_by('timestamp'))

    if request.method == 'GET':
        chapter_form = ChapterForm()
    elif request.method == 'POST':
        if already_written:
            return render_to_response('error.html', 
                                      {'error_code': '403',
                                       'error_explanation': 
                                         msg.ERR_ALREADY_WRITTEN_EXPL},
                                       context_instance=RequestContext(request))
        chapter_form = ChapterForm(request.POST, request.FILES)
        
        user_entered_code = request.REQUEST.get('code', None)
        user_entered_code = user_entered_code if user_entered_code == secret_code else ''
        if chapter_form.is_valid():
            # Check to make sure that the code is legit.
            if chapter_form.cleaned_data['code'] != secret_code:
                return render_to_response('error.html',
                                          {'error_code': '401',
                                           'error_explanation': msg.ERR_WRONG_CODE_EXPL},
                                           context_instance=RequestContext(request))
            new_chapter = chapter_form.save(commit=False)
            new_chapter.lilguy = lilguy
            new_chapter.save()
            # Update the guy's location in the DB
            lilguy.current_lat = new_chapter.found_at_lat
            lilguy.current_lon = new_chapter.found_at_lon
            lilguy.save()
            request.session['has_made_chapter_'+url_code] = True
            return HttpResponseRedirect("/lilguys/" + "g/" + url_code)

    # Make a list of all the gps coordinates.
    journey_coords = json.dumps(
            map(lambda c: {'lat': c.found_at_lat, 'lng': c.found_at_lon}, chapters))
    return render_to_response('display_guy.html',
                              {'lilguy': lilguy, 
                               'url_code': url_code,
                               'already_written': already_written,
                               'user_entered_code': user_entered_code,
                               'chapters': chapters,
                               'journey_coords': journey_coords,
                               'chapter_form': chapter_form},
                               context_instance=RequestContext(request))

def about_us(request):
    return render_to_response('about.html',
                              {}, context_instance=RequestContext(request))

guytracker/templates/about.html
{% extends "base.html" %}

    
    {% block nav-about %}
      <li class="active"><a href="/lilguys/about">about</a></li>
    {% endblock %}

    {% block mapwrap %}{% endblock %}

    {% block title %}about{% endblock %}

    {% block content %}

      <div id="about">
        <h1>about lilguys</h1>
        <p>Hello! This is a collaborative art project from <a href="http://convox.org">Convox</a>. We and assorted friends crafted a bunch of little guys, and let them go free to wander the world! We hope that we can all write their stories together. You can see all the guys out there on <a href="/lilguys/#allguysmap">this map</a>. </p>
        <p>The guys have little url tags attached to them and secret codes etched into their little belly/body/body-equivalents, so people who find them can contribute the next chapter in that guy's adventure before leaving them somewhere to wander until they meet someone else! Hopefully some guys will get to travel the world, or at least delight a random passerby with their company. </p>

        <h1>we made this</h1>
        <p>We are <a href="https://twitter.com/carsonkmcneil">Carson</a> & <a href="https://twitter.com/daiyitastic">daiyi</a>, two aspiring humans living in San Francisco. We were walking around the city when we found chalk someone had left on the street, where random people had started contributing to collaborative sidewalk doodles. We want to spread little spontaneous art things all over! We live in <a href="http://convox.org">Convox</a>, but only until we can achieve our dream treehouse on a whale.</p>

        <p>Here's us on the happiest day of the year (daylight savings' eve):</p>

        <img class="img-responsive" src="{{ MEDIA_URL }}us.png"/>
      </div>

    {% endblock %}

guytracker/templates/all_guys.html
{% extends "base.html" %}

{% block title %}lil guys all over the place{% endblock %}

{% block map %}
<div id="map-canvas"></div>
{% endblock %}


{% block content-wrap %}

<div class="container">
    <h1>lil guys <small>made in San Francisco, passed from friend to stranger, seeing how far they can go in the world</small></h1>

    <div id="recent-chapters">

      <div class="row">
        <div class="col-md-12 col-sm-12">
          <h2>Recent adventures!</h2><br>
        </div>
      </div>

      {% for chapter in recent_chapters %}      
      <a href="/lilguys/g/{{ chapter.url }}#{{ chapter.timestamp|date:'U' }}">
        <div class="panel panel-recent-chapter">
          <div class="row">
            <div class="recent-avatar">
              <img src="{{ chapter.lilguy.pic_180.url }}" class="img-responsive">
            </div>
            <div class="recent-synopsis">
              <div class="panel-body">
                <p><b>{{ chapter.lilguy.name }} made an appearance in  
                    {{ chapter.location.city }}  on 
                    {{ chapter.timestamp|date:"F j" }}:</b></p>
                {{ chapter.story_text|truncatewords_html:40 }}
              </div>
            </div>
          </div>
        </div>
      </a>
      {% endfor %}

    </div>
</div>

<div class="container-fluid all-guys">
  <div class="container">
    <h2>Some more guys</h2>
    <div id="guy-grid-container">
      <div id="guy-grid">
        <div class="row">
          {% for code, name_pic in lilguy_url_code_to_name_pic.items %}
          <div class="col-md-4 col-sm-4 col-xs-4 guy-grid-box">
            <a href="/lilguys/g/{{ code }}">
              <img class="img-responsive" src="{{ name_pic.1.url }}" alt="">
            </a>
            <h3>
              <a href="/lilguys/g/{{ code }}">{{ name_pic.0 }}</a>
            </h3>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block javascript %}
<script>
function initialize_map() {
    var mapOptions = {
        center: { lat: -34.397, lng: 150.644},
        zoom: 8,
        disableDefaultUI: true,
        mapTypeControl: false, 
        zoomControl: true,
        zoomControlOptions: {
            style: google.maps.ZoomControlStyle.LARGE,
            position: google.maps.ControlPosition.LEFT_BOTTOM
        },
        streetViewControl: false,
    };
    var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

    var lilguys = {{ lilguys_js|safe }};
    var markers = [];
    var bounds = new google.maps.LatLngBounds();
    for (var i = 0; i < lilguys.length; i++) {
        var coord = new google.maps.LatLng(lilguys[i].current_lat, 
                                           lilguys[i].current_lon);
        markers.push(new google.maps.Marker({position: coord, map: map}));
        bounds.extend(coord);
    }
    map.fitBounds(bounds);
}
google.maps.event.addDomListener(window, 'load', initialize_map);
</script>
{% endblock %}

guytracker/templates/base.html
{% load dajaxice_templatetags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <link rel="icon" href="{{ STATIC_URL }}favicon.ico">

    <title>{% block title %}{% endblock %} [ lilguys ]</title>

    <!-- bootstrap core css -->
    <link rel="stylesheet" href="{{ STATIC_URL}}bootstrap.min.css">

    <!-- <link rel="stylesheet" href="/bootstrap_custom.css"> -->
    <link href='https://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>  
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap_custom.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}guy_map.css">
    
    {% dajaxice_js_import %}
  </head>

  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/lilguys">lilguys</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% block nav-about %}
              <li><a href="/lilguys/about">about</a></li>
            {% endblock %}
              <li><a href="/lilguys/#recent-chapters">recent adventures</a></li>
              <li><a href="https://github.com/cmcneil/lilguys">github</a></li>
              <!--<li><a href="https://twitter.com/lilguytracker">@lilguytracker</a></li>-->
          </ul>
        </div><!--/.nav-collapse -->
        
      </div>
    </nav>
 
    {% block mapwrap %}
    <a name="allguysmap"></a>
    <div id="mapwrap">
      <div class="jumbotron">
        {% block map %}
          <iframe
            width="100%"
            height="500px"
            frameborder="0" style="border:0"
            src=" https://www.google.com/maps/embed/v1/place?key=AIzaSyAMi4n47QH6dNiVtxHe0tpV5RZZup6fLY8&q=37.775102,-122.431142">
          </iframe>
        {% endblock %}
      </div>

      {% block avatar %}{% endblock %}

    </div>
    <div class="map-end"></div>
    {% endblock %}



    {% block content-wrap %}
    <div class="container">
      {% block content %}{% endblock %}
    </div>
    {% endblock %}
    


    <footer id="footer">
      <a name="whats-going-on"></a>
      <div class="container-fluid">
        {% block footer %}
        <div id="footer-about">  
          <p></p>
        </div>
        {% endblock %}
        <div id="footer-nav" class="text-center">
          <a href="/lilguys/about">about</a> this art project 
          &middot; on <a href="https://github.com/cmcneil/lilguys">github</a> 
          &middot; <a href="https://twitter.com/lilguytracker">@lilguytracker</a> 
          &middot; made with &lt;3 by <a href="https://twitter.com/carsonkmcneil">carson</a> & <a href="https://twitter.com/daiyitastic">daiyi</a> 
          &middot hosted on <a href="http://convox.org">convox</a> in SF
        </div>
      </div>
    </footer>



    <!-- Bootstrap core JavaScript  
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug
         http://getbootstrap.com/getting-started/#support-ie10-width -->
    <script type="text/javascript">
         (function () {
         'use strict';
         if (navigator.userAgent.match(/IEMobile\/10\.0/)) {
         var msViewportStyle = document.createElement('style')
         msViewportStyle.appendChild(
         document.createTextNode(
         '@-ms-viewport{width:auto!important}'
         )
         )
         document.querySelector('head').appendChild(msViewportStyle)
         }
         })();
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAMi4n47QH6dNiVtxHe0tpV5RZZup6fLY8"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

guytracker/templates/display_guy.html
{% extends "base.html" %}
    
    {% block title %}{{ lilguy.name }}'s adventure so far{% endblock %}

    {% block map %}
    <div id="map-canvas"></div>
    {% endblock %}


    {% block avatar %}
      <div id="avwrap">
        <div id="avatar" class="center-block">
          <a href="">
            <img src="{{ lilguy.pic.url }}" id="img-avatar" class="img-thumbnail">
          </a>
        </div>
      </div>
    {% endblock %}
 


    {% block content %}
    <div id="chapters-wrap">

      <h1>This lil guy's name is <em>{{ lilguy.name }}</em>. <small>This is their adventure thus far, as documented by a stranger like you.</small></h1>


      <div class="container">
        {% for chapter in chapters %}
        <div id="{{ chapter.timestamp|date:'U' }}">
          <div class="chapter">
            <div class="panel panel-default">
              {% if chapter.picture_600 %}
              <img class="img-responsive" src="{{ chapter.picture_600.url }}">
              {% elif chapter.picture %}
              <img class="img-responsive" src="{{ chapter.picture.url }}">
              {% endif %}
              
              <div class="panel-body">
                {% if chapter.title %}
                <h2>{{ chapter.title }}</h2>
                {% endif %}
                <h5>{{ chapter.timestamp|date:"F j, Y" }}</h5>
                <p>{{ chapter.story_text|linebreaks }}</p>
              </div>

              <ul class="list-group">
                <li class="list-group-item">Found at ({{ chapter.found_at_lon }}, {{ chapter.found_at_lat}}) 
                </li>

              </ul>
            </div>
          </div>
        </div>
        {% endfor %}

 
        {% if not already_written %}
        <div class="panel panel-default" id="panel-add-chapter">

          <div class="panel-body">
              <!-- Hidden field stores lilguy's url_code for auth against entered code.
                   Think of it as the 'username' to the password that the user enters. -->
              <input id="url_code" type="hidden" value="{{ url_code }}"/>

              <div id="panel-code-input" class="form-group">
                  <label for="code_input"><h2>I found this little guy <br><small><em>search my tiny body for a mysterious code.</em></small></h2></label>
                  <br><input type="text" id="code_input" value="{{ user_entered_code }}" />
                <div id="checking-code">
                  <span class="glyphicon glyphicon-refresh"></span>
                </div>
              </div>
              
              <form id="add-chapter" enctype="multipart/form-data" action="/lilguys/g/{{ url_code }}/" method="post">
                {% csrf_token %}
                {{ chapter_form.code }}
                <div class="form-group">
                  <h3>Add a chapter to the story of this guy's adventure!</h3>
                </div>

                <div class="form-group">  
                  <label for="id_picture"><b>picture</b> <span class="form-advice">of this guy's intrepid exploration of the world under your care</span></label>
                  {{ chapter_form.picture }}
                  {% if chapter_form.picture.errors %}
                  <div class="alert alert-danger" role="alert">
                    {{ chapter_form.picture.errors }}</div>
                  {% endif %}
                </div>

                <div class="form-group expand">
                    <label for="id_title"><b>title</b> <span class="form-advice"><i>(optional)</i></span></label>
                    {{ chapter_form.title }}
                    {% if chapter_form.title.errors %}
                    <div class="alert alert-danger" role="alert">
                      {{ chapter_form.title.errors }}</div>
                    {% endif %}
                </div>

                <div class="form-group">                    
                  <label for="id_story"><b>story</b> <span class="form-advice"></span></label>
                  {{ chapter_form.story_text }}
                  {% if chapter_form.story_text.errors %}
                  <div class="alert alert-danger" role="alert">
                    {{ chapter_form.story_text.errors }}</div>
                  {% endif %}
                </div>

                <div class="form-group">  
                  <label for="id_found_at_lat"><b>where</b> <span class="form-advice">did you find me? <i>(click map)</i></span</label>
                  {{ chapter_form.found_at_lat}}
                  {{ chapter_form.found_at_lon }}
                  {% if chapter_form.found_at_lat.errors %}
                  <div class="alert alert-danger" role="alert">
                    {{ chapter_form.found_at_lat.errors }}
                    {{ chapter_form.found_at_lon.errors }} </div>
                  {% endif %}
                </div>

                <div id="id_map_wrap">
                  <div id="id_map"></div>
                </div><br>

                <div class="form-group input-block">
                  <label for="id_email"><b>email</b> <span class="form-advice">for adventure updates <i>(optional)</i></span></label>
                  {{ chapter_form.email }}
                  {% if chapter_form.email.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ chapter_form.email.errors }}</div>
                  {% endif %}
                </div>

                <input class="btn btn-default pull-right" type="submit" value="Add story!"></input>
              </form>
            
          </div>
      </div>
      {% endif %}
      </div> 
    </div> <!-- end #chapters-wrap -->
    {% endblock %}


    {% block javascript %} 
    <script src="{{ STATIC_URL  }}maps_location_widget.js"></script> 
    <script src="{{ STATIC_URL }}add_chapter.js"></script>
    <script>
        {% if user_entered_code %}
            $(document).ready(function() {   
                code_validation_callback({'status': 'VALID'}); 
            });
        {% endif %}
        function initialize_map() {
            var mapOptions = {
                center: { lat: {{ lilguy.current_lat }},
                          lng: {{ lilguy.current_lon}}
                          },
                zoom: 15,
                disableDefaultUI: true,
                mapTypeControl: false, 
                zoomControl: true,
                zoomControlOptions: {
                    style: google.maps.ZoomControlStyle.LARGE,
                    position: google.maps.ControlPosition.LEFT_BOTTOM
                },
                streetViewControl: false,
            };
            var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

            // Make the line that will trace the guys route:
            var lineSymbol = {
                    path: google.maps.SymbolPath.FORWARD_CLOSED_ARROW
            };
            var polyOptions = {
                icons: [{
                    icon: lineSymbol,
                    offset: '100px',
                    repeat: '150px'
                }],
                strokeColor: '#3366FF',
                srokeOpacity: 1.0,
                strokeWeight: 3
            };
            var poly = new google.maps.Polyline(polyOptions);
            poly.setMap(map);

            // Make an array of everywhere the lilguys has been.
            var journey = {{ journey_coords|safe }};
            var journey_markers = [];
            var bounds = new google.maps.LatLngBounds(); //Object used to fit map to pts.
            // Draw all the placemarks
            for (var i = 0; i < journey.length; i++) {
                var coord = new google.maps.LatLng(journey[i].lat, journey[i].lng);
                journey_markers.push(new google.maps.Marker({position: coord, map:map}));
                var path = poly.getPath();
                path.push(coord);
                bounds.extend(coord);
            }
            // size the map so it contains all the points:
            map.fitBounds(bounds);
        }
        google.maps.event.addDomListener(window, 'load', initialize_map);
    </script>
    {% endblock %} 

guytracker/templates/error.html
{% extends "base.html" %}

    {% block title %}Error {{ error_code }}{% endblock %}
    {% block map %}
    <!-- No map! It's an error page! -->
    {% endblock %}

    {% block content %}
    <h1>Error {{ error_code }}</h1>
    You've hit an error! Hit the lilguys button in the header to go back to the main site.
    We don't necessarily know what went wrong, but here's our best guess at what it was and how to fix it:
    </br></br><i>{{ error_explanation }}</i>
    {% endblock %}